var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da="./this.program",ea=(a,b)=>{throw b;},fa=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?fa=__filename:ba&&(fa=self.location.href);var ha="",ia,ka;
if(ca){var fs=require("fs");ha=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var h=console.log.bind(console),l=console.error.bind(console),ma,q=!1,na,la=a=>a.startsWith("file://"),t,v,oa,pa,w,x,qa,ra;
function sa(){var a=ta.buffer;t=new Int8Array(a);oa=new Int16Array(a);g.HEAPU8=v=new Uint8Array(a);pa=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);qa=new Float32Array(a);new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}function z(a){g.onAbort?.(a);a="Aborted("+a+")";l(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ua&&ma)a=new Uint8Array(ma);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function xa(a){var b=ua;if(!ma&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(g)},Aa=[],Ba=[],Ca=()=>{var a=g.preRun.shift();Ba.push(a)},A=0,Da=null,Ea=!0,Fa=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c};class Ga{constructor(a){this.ib=a-24}}
var Ha=0,Ia=0,C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.codePointAt(f);if(127>=k){if(c>=d)break;b[c++]=k}else if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6;b[c++]=128|k&63}else if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12;b[c++]=128|k>>6&63;b[c++]=128|k&63}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63;b[c++]=128|k>>6&63;b[c++]=128|k&63;f++}}b[c]=0;return c-e},Ja=a=>{a instanceof ya||"unwind"==a||ea(1,a)},Ka=a=>{na=a;Ea||(g.onExit?.(a),q=!0);ea(a,
new ya(a))},La=()=>{if(!Ea)try{var a=na;na=a;Ka(a)}catch(b){Ja(b)}},Ua=(a,b)=>{Ma=a;Na=b;if(Oa)if(Pa||=!0,0==a)E=function(){setTimeout(Qa,Math.max(0,Ra+b-performance.now())|0)};else if(1==a)E=function(){Sa(Qa)};else if(2==a){if(!Ta)if(globalThis.setImmediate)Ta=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ta=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);
postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}E=function(){Ta(Qa)}}},Pa=!1,E=null,Va=0,Oa=null,Xa=0,Ma=0,Na=0,F=0,Ya=[],Za=[],$a=[],ab=0;function Sa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var bb={},Ra,Qa,Ta,cb,db=(a,b,c,d,e)=>{function f(){return k<Va?(La(),!1):!0}Oa=a;Xa=d;var k=Va;Pa=!1;Qa=function(){if(!q)if(0<Ya.length){var n=Ya.shift();n.sc(n.cc);if(cb){var m=cb,p=0==m%1?m-1:Math.floor(m);cb=n.mc?p:(8*m+(p+.5))/9}g.setStatus&&(n=g.statusMessage||"Please wait...",m=cb??0,p=bb.pc??0,m?m<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(n):g.setStatus(""));f()&&setTimeout(Qa,0)}else if(f())if(F=F+1|0,1==Ma&&1<Na&&0!=F%Na)E();else{0==Ma&&(Ra=performance.now());
a:if(!q){for(n of Za)if(!1===n())break a;if(!q)try{a(),La()}catch(u){Ja(u)}for(m of $a)m()}f()&&E()}};e||(0<b?Ua(0,1E3/b):Ua(1,1),E());if(c)throw"unwind";},eb={},gb=()=>{if(!fb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in eb)void 0===eb[b]?delete a[b]:a[b]=eb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);fb=c}return fb},fb,hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=[null,[],[]],G,jb=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},kb=1,lb=[],H=[],mb=[],nb=[],I=[],ob=[],pb=[],qb=a=>{for(var b=kb++,c=a.length;c<b;c++)a[c]=null;return b},rb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=G[c](),k=f&&qb(d);f?(f.name=k,d[k]=f):J||=1282;w[b+4*e>>2]=k}},tb=(a,b)=>{a.Xa||(a.Xa=a.getContext,a.getContext=function(d,e){e=a.Xa(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?sb(c,b):0},sb=(a,b)=>{var c=qb(pb),d={handle:c,attributes:b,
version:b.Xb,jb:a};a.canvas&&(a.canvas.ac=d);pb[c]=d;if("undefined"==typeof b.Ub||b.Ub)if((a=d)||(a=ub),!a.Wb){a.Wb=!0;b=a.jb;b.yc=b.getExtension("WEBGL_multi_draw");b.rc=b.getExtension("EXT_polygon_offset_clamp");b.qc=b.getExtension("EXT_clip_control");b.Bc=b.getExtension("WEBGL_polygon_mode");b.nc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.xc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Cb=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(2>a.version||!b.Cb)b.Cb=b.getExtension("EXT_disjoint_timer_query");for(var e of jb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},vb={},J,ub,wb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),xb=a=>{a-=5120;return 0==a?t:1==a?v:2==a?oa:4==a?w:6==a?qa:5==a||28922==a||28520==a||30779==a||30782==a?x:pa},yb=a=>{var b=G.Tb;if(b){var c=b.$a[a];"number"==typeof c&&(b.$a[a]=c=G.getUniformLocation(b,b.Pb[a]+(0<c?`[${c}]`:"")));return c}J||=1282};
function zb(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Ab=a=>{setTimeout(()=>{if(!q)try{a(),La()}catch(b){Ja(b)}},1E4)},Bb=[],K=!1,Cb=!1,Db=[];
function Eb(){function a(){Cb=document.pointerLockElement===g.canvas}if(!Fb){Fb=!0;Bb.push({canHandle:function(c){return!g.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Gb(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Gb(d)}));var f=URL.createObjectURL(e);return new Promise((k,n)=>{var m=new Image;m.onload=()=>{var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,
0,0);URL.revokeObjectURL(f);k(c)};m.onerror=()=>{l(`Image ${f} could not be decoded`);n()};m.src=f})}});Bb.push({canHandle:function(c){return!g.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){k||(k=!0,e(c))}var k=!1,n=new Blob([c],{type:Gb(d)});n=URL.createObjectURL(n);var m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!k){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="data:audio/x-"+d.slice(-3)+";base64,",u="",r=0,y=0,D=0;D<c.length;D++)for(r=r<<8|c[D],y+=8;6<=y;){var ja=r>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[ja]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],u+="=");m.src=p+u;f(m)}};m.src=n;Ab(()=>{f(m)})})}});var b=g.canvas;b&&(document.addEventListener("pointerlockchange",
a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Cb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Hb(a){var b={antialias:1<L[135181],depth:0<L[135173],stencil:0<L[135174],alpha:0<L[135172]};if(!g.ctx||a!=g.canvas){var c,d={antialias:!1,alpha:!1,Xb:2};if(b)for(var e in b)d[e]=b[e];if("undefined"!=typeof vb&&(c=tb(a,d)))var f=pb[c].jb;f&&(g.ctx=f,ub=pb[c],g.ctx=G=ub?.jb,Db.forEach(k=>k()),Eb())}}var Ib=!1,M=void 0,N=void 0;
function Jb(a,b){function c(){K=!1;var f=d.parentNode;zb()===f?(d.exitFullscreen=Kb,M&&d.requestPointerLock(),K=!0,N?Lb():O(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),N?Mb():O(d));g.onFullScreen?.(K);g.onFullscreen?.(K)}M=a;N=b;"undefined"==typeof M&&(M=!0);"undefined"==typeof N&&(N=!1);var d=g.canvas;Ib||(Ib=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",
c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Kb(){if(!K)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}function Gb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var Nb=0,Ob=0,Pb=0,Qb=0;
function Rb(a,b){var c=g.canvas,d=c.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+d.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+d.top;a*=c.width/d.width;b*=c.height/d.height;return{x:a,y:b}}function Sb(a,b){const {x:c,y:d}=Rb(a,b);Pb=c-Nb;Qb=d-Ob;Nb=c;Ob=d}
function Tb(a){Cb?("mousemove"!=a.type&&"mozMovementX"in a?Pb=Qb=0:(Pb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Qb=a.movementY||a.mozMovementY||a.webkitMovementY||0),Nb+=Pb,Ob+=Qb):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.Ac,void 0!==a&&Rb(a.pageX,a.pageY)):Sb(a.pageX,a.pageY)}var Ub=[];function P(){var a=g.canvas;Ub.forEach(b=>b(a.width,a.height))}function Lb(){"undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608);O(g.canvas);P()}
function Mb(){"undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]&-8388609);O(g.canvas);P()}
function O(a,b,c){b&&c?(a.zb=b,a.ub=c):(b=a.zb,c=a.ub);var d=b,e=c;0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if(zb()===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}N?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=
c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Fb;
function Vb(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.bb=!1;this.Ob=this.Nb=0;this.width=b;this.height=c;this.tb=d;this.sb=e;this.xb=b;this.wb=c;this.title=f;this.attributes={...L};this.buttons=0;this.keys=[];this.ob=[];this.title=null;this.Ab=this.Gb=this.pb=this.Mb=this.ab=this.mb=this.Kb=this.Rb=this.Eb=this.Sb=0}
var Xb=a=>{var b=hb(a)+1,c=Wb(b);c&&C(a,v,c,b);return c},Yb=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Zb=a=>{(Zb=Yb())(a)},$b=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ac=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=$b(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+
a},bc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},cc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=$b(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},dc=[],ec=a=>{var b=Array(hb(a)+1);a=C(a,b,0,b.length);b.length=
a;return b},fc=[];function gc(a,b){fc[a]={input:[],output:[],Za:b};hc(a,ic)}
var ic={open(a){var b=fc[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close(a){a.tty.Za.fsync(a.tty)},fsync(a){a.tty.Za.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Za.Fb)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Za.Fb(a.tty)}catch(n){throw new Q(29);}if(void 0===k&&0===e)throw new Q(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Za.vb)throw new Q(60);try{for(var e=0;e<d;e++)a.tty.Za.vb(a.tty,b[c+e])}catch(f){throw new Q(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},jc={Fb(){a:{if(!dc.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}dc=ec(a)}a=dc.shift()}return a},vb(a,b){null===b||10===b?(h(B(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(h(B(a.output)),a.output=[])},uc(){return{ic:25856,kc:5,hc:191,jc:35387,fc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},vc(){return 0},wc(){return[24,80]}},kc={vb(a,b){null===b||10===b?(l(B(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(l(B(a.output)),a.output=[])}},R={Ta:null,Va(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.Ta||(R.Ta={dir:{node:{Wa:R.Pa.Wa,Ua:R.Pa.Ua,
lookup:R.Pa.lookup,gb:R.Pa.gb,rename:R.Pa.rename,unlink:R.Pa.unlink,rmdir:R.Pa.rmdir,readdir:R.Pa.readdir,symlink:R.Pa.symlink},stream:{Sa:R.Qa.Sa}},file:{node:{Wa:R.Pa.Wa,Ua:R.Pa.Ua},stream:{Sa:R.Qa.Sa,read:R.Qa.read,write:R.Qa.write,Ib:R.Qa.Ib,Lb:R.Qa.Lb}},link:{node:{Wa:R.Pa.Wa,Ua:R.Pa.Ua,readlink:R.Pa.readlink},stream:{}},Bb:{node:{Wa:R.Pa.Wa,Ua:R.Pa.Ua},stream:lc}});c=mc(a,b,c,d);16384===(c.mode&61440)?(c.Pa=R.Ta.dir.node,c.Qa=R.Ta.dir.stream,c.Oa={}):32768===(c.mode&61440)?(c.Pa=R.Ta.file.node,
c.Qa=R.Ta.file.stream,c.Ra=0,c.Oa=null):40960===(c.mode&61440)?(c.Pa=R.Ta.link.node,c.Qa=R.Ta.link.stream):8192===(c.mode&61440)&&(c.Pa=R.Ta.Bb.node,c.Qa=R.Ta.Bb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Oa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},tc(a){return a.Oa?a.Oa.subarray?a.Oa.subarray(0,a.Ra):new Uint8Array(a.Oa):new Uint8Array(0)},Pa:{Wa(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=
4096:32768===(a.mode&61440)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ua(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ra!=b&&(0==b?(a.Oa=null,a.Ra=0):(c=a.Oa,a.Oa=new Uint8Array(b),c&&a.Oa.set(c.subarray(0,Math.min(b,a.Ra))),a.Ra=b)))},lookup(){R.nb||(R.nb=new Q(44),R.nb.stack="<generic error, no stack>");
throw R.nb;},gb(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=nc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.Oa)throw new Q(55);e=oc(d.parent.id,d.name);if(S[e]===d)S[e]=d.Ya;else for(e=S[e];e;){if(e.Ya===d){e.Ya=d.Ya;break}e=e.Ya}}delete a.parent.Oa[a.name];b.Oa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Oa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=nc(a,b),d;for(d in c.Oa)throw new Q(55);delete a.Oa[b];a.ctime=
a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Oa)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},Qa:{read(a,b,c,d,e){var f=a.node.Oa;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Oa||
a.Oa.subarray)){if(f)return a.Oa=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Oa=b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Oa.set(b.subarray(c,c+d),e),d}f=e+d;var k=a.Oa?a.Oa.length:0;k>=f||(f=Math.max(f,k*(1048576>k?2:1.125)>>>0),0!=k&&(f=Math.max(f,256)),k=a.Oa,a.Oa=new Uint8Array(f),0<a.Ra&&a.Oa.set(k.subarray(0,a.Ra),0));if(a.Oa.subarray&&b.subarray)a.Oa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Oa[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},Sa(a,b,c){1===c?b+=a.position:2===
c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new Q(28);return b},Ib(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.Oa;if(e&2||!a||a.buffer!==t.buffer){d=!0;z();e=void 0;if(!e)throw new Q(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{ib:e,bc:d}},Lb(a,b,c,d){R.Qa.write(a,b,0,d,c,!1);return 0}}},pc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qc=null,rc={},sc=[],tc=
1,S=null,uc=!1,vc=!0,wc={},Q=class{name="ErrnoError";constructor(a){this.Db=a}},xc=class{Xa={};node=null;get flags(){return this.Xa.flags}set flags(a){this.Xa.flags=a}get position(){return this.Xa.position}set position(a){this.Xa.position=a}},yc=class{Pa={};Qa={};hb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Va=a.Va;this.id=tc++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=
-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function T(a,b={}){if(!a)throw new Q(44);b.rb??(b.rb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=qc,e="/",f=0;f<a.length;f++){var k=f===a.length-1;if(k&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=bc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=ac(e+"/"+a[f]);try{d=nc(d,a[f])}catch(n){if(44===n?.Db&&k&&b.Zb)return{path:e};throw n;}!d.hb||k&&!b.rb||(d=d.hb.root);if(40960===(d.mode&61440)&&(!k||b.qb)){if(!d.Pa.readlink)throw new Q(52);
d=d.Pa.readlink(d);"/"===d.charAt(0)||(d=bc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new Q(32);}function zc(a){for(var b;;){if(a===a.parent)return a=a.Va.Jb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function oc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}
function nc(a,b){var c=16384===(a.mode&61440)?(c=Ac(a,"x"))?c:a.Pa.lookup?0:2:54;if(c)throw new Q(c);for(c=S[oc(a.id,b)];c;c=c.Ya){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Pa.lookup(a,b)}function mc(a,b,c,d){a=new yc(a,b,c,d);b=oc(a.parent.id,a.name);a.Ya=S[b];return S[b]=a}function Bc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Ac(a,b){if(vc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cc(a,b){if(16384!==(a.mode&61440))return 54;try{return nc(a,b),20}catch(c){}return Ac(a,"wx")}function Dc(a){a=sc[a];if(!a)throw new Q(8);return a}function Ec(a,b){var c=null?.Qa.Ua,d=c?null:a;c??=a.Pa.Ua;if(!c)throw new Q(63);c(d,b)}var lc={open(a){a.Qa=rc[a.node.rdev].Qa;a.Qa.open?.(a)},Sa(){throw new Q(70);}};
function hc(a,b){rc[a]={Qa:b}}function Fc(a,b){var c="/"===b;if(c&&qc)throw new Q(10);if(!c&&b){var d=T(b,{rb:!1});b=d.path;d=d.node;if(d.hb)throw new Q(10);if(16384!==(d.mode&61440))throw new Q(54);}b={type:a,zc:{},Jb:b,Yb:[]};a=a.Va(b);a.Va=b;b.root=a;c?qc=a:d&&(d.hb=b,d.Va&&d.Va.Yb.push(b))}
function Gc(a,b,c){var d=T(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new Q(28);if("."===a||".."===a)throw new Q(20);var e=Cc(d,a);if(e)throw new Q(e);if(!d.Pa.gb)throw new Q(63);return d.Pa.gb(d,a,b,c)}function U(a){return Gc(a,16895,0)}function Hc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Gc(a,b|8192,c)}
function Ic(a,b){if(!cc(a))throw new Q(44);var c=T(b,{parent:!0}).node;if(!c)throw new Q(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Cc(c,b);if(d)throw new Q(d);if(!c.Pa.symlink)throw new Q(63);c.Pa.symlink(c,b,a)}
function Jc(a,b,c=438){if(""===a)throw new Q(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=T(a,{qb:!(b&131072),Zb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new Q(20);}else{if(e)throw new Q(31);d=Gc(a,c|511,0);f=!0}if(!d)throw new Q(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new Q(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Bc(b)||b&576)?31:Ac(d,Bc(b)):44))throw new Q(e);if(b&512&&!f){e=d;e="string"==typeof e?T(e,{qb:!0}).node:e;if(16384===(e.mode&61440))throw new Q(31);if(32768!==(e.mode&61440))throw new Q(28);var k=Ac(e,"w");if(k)throw new Q(k);Ec(e,{size:0,timestamp:Date.now()})}b&=-131713;e={node:d,path:zc(d),flags:b,seekable:!0,position:0,Qa:d.Qa,$b:[],error:!1};k=-1;e=Object.assign(new xc,e);if(-1==k)a:{for(k=0;4096>=k;k++)if(!sc[k])break a;
throw new Q(33);}e.fd=k;sc[k]=e;e.Qa.open&&e.Qa.open(e);f&&(c&=511,d="string"==typeof d?T(d,{qb:!0}).node:d,Ec(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),oc:void 0}));!g.logReadFiles||b&1||a in wc||(wc[a]=1);return e}function Kc(){var a="/";a="string"==typeof a?a:zc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ac(a+"/"+c);try{U(a)}catch(d){if(20!=d.Db)throw d;}}}}
function V(a,b,c){a=ac("/dev/"+a);var d=pc(!!b,!!c);V.Hb??(V.Hb=64);var e=V.Hb++<<8|0;hc(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,k,n,m){for(var p=0,u=0;u<m;u++){try{var r=b()}catch(y){throw new Q(29);}if(void 0===r&&0===p)throw new Q(6);if(null===r||void 0===r)break;p++;k[n+u]=r}p&&(f.node.atime=Date.now());return p},write(f,k,n,m){for(var p=0;p<m;p++)try{c(k[n+p])}catch(u){throw new Q(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return p}});Hc(a,d,e)}
var W=null,Lc=null,X=null,Mc=null,L=null,Nc=null,Oc={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},Pc=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;
case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;
case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;
case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;
case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;default:return-1}},
Qc=()=>{var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},Rc=a=>{W&&W.Ab&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Y.get(W.Ab)(W.id,a))},Sc=(a,b)=>{if(W){var c=Pc(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.ob[a]=b;W.Gb&&(d&&(b=2),Y.get(W.Gb)(W.id,c,a,b,Qc()))}}},Uc=()=>{Tc()},Vc=()=>{Tc()},Wc=a=>{Sc(a.keyCode,1);"Backspace"!=a.key&&"Tab"!=a.key||a.preventDefault()},Xc=a=>{Sc(a.keyCode,0)},Yc=()=>{if(W)for(var a=0;a<
W.ob.length;++a)W.ob[a]&&Sc(a,0)},Zc=a=>{if(W){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(Nc===c.identifier){Sb(c.pageX,c.pageY);b=!0;break}if(!b)return}else Tb(a);a.target==g.canvas&&W.mb&&W.mb&&Y.get(W.mb)(W.id,Nb,Ob)}},$c=a=>{W&&a.target==g.canvas&&W.ab&&Y.get(W.ab)(W.id,1)},ad=a=>{W&&a.target==g.canvas&&W.ab&&Y.get(W.ab)(W.id,0)},bd=(a,b)=>{if(W&&a.target==g.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();
var d=!1;if(null===Nc&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],Nc=d.identifier,Sb(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(Nc===e.identifier){Nc=null;d=!0;break}if(!d)return}else Tb(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else W.buttons&=~(1<<c);W.Kb&&Y.get(W.Kb)(W.id,c,b,Qc())}},cd=a=>{W&&bd(a,1)},dd=a=>{W&&bd(a,0)},ed=a=>{var b=0;switch(a.type){case "DOMMouseScroll":b=
a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:z("unrecognized mouse wheel delta mode: "+a.deltaMode)}break;default:z("unrecognized mouse wheel event: "+a.type)}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(W&&W.Mb&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;Y.get(W.Mb)(W.id,b,c);a.preventDefault()}},fd=(a,b,c,d)=>{if(W){var e=!1;zb()?W.bb||(e=
a!=screen.width||b!=screen.height,W.Nb=W.x,W.Ob=W.y,W.xb=W.width,W.wb=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.bb=!0):1==W.bb&&(e=a!=W.xb||b!=W.wb,W.x=W.Nb,W.y=W.Ob,W.width=W.xb,W.height=W.wb,W.bb=!1);if(e)O(g.canvas,W.width,W.height),P();else if(W.width!=a||W.height!=b||W.tb!=c||W.sb!=d)W.width=a,W.height=b,W.tb=c,W.sb=d,W&&W.Sb&&Y.get(W.Sb)(W.id,W.width,W.height),W&&W.Eb&&Y.get(W.Eb)(W.id,W.tb,W.sb)}},Z={},gd=[],hd=null,Tc=()=>{if(F!==hd||!F){gd=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads||[];hd=F;for(var a=0;a<gd.length;++a){var b=gd[a];if(b){Z[a]||(h("glfw joystick connected:",a),Z[a]={id:Xb(b.id),ec:b.buttons.length,dc:b.axes.length,buttons:Wb(b.buttons.length),axes:Wb(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)t[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)qa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(h("glfw joystick disconnected",a),jd(Z[a].id),jd(Z[a].buttons),jd(Z[a].axes),delete Z[a])}}},kd=a=>{function b(n){var m="/.glfw_dropped_files/"+
n.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=r=>{if(2!=p.readyState)++f,h("failed to read dropped file: "+n.name+": "+p.error);else{var y=new Uint8Array(r.target.result),D={};D.flags=D.flags||577;r=Jc(m,D.flags,D.mode);"string"==typeof y&&(y=new Uint8Array(ec(y)));if(ArrayBuffer.isView(y)){var ja=y;y=y.byteLength;var wd=D.lc,Wa=void 0;if(0>y||0>Wa)throw new Q(28);if(null===r.fd)throw new Q(8);if(0===(r.flags&2097155))throw new Q(8);if(16384===(r.node.mode&61440))throw new Q(31);if(!r.Qa.write)throw new Q(28);
if(r.seekable&&r.flags&1024){if(null===r.fd)throw new Q(8);if(!r.seekable||!r.Qa.Sa)throw new Q(70);r.position=r.Qa.Sa(r,0,2);r.$b=[]}D="undefined"!=typeof Wa;if(!D)Wa=r.position;else if(!r.seekable)throw new Q(70);ja=r.Qa.write(r,ja,0,y,Wa,wd);D||(r.position+=ja)}else z("Unsupported data type");if(null===r.fd)throw new Q(8);r.Vb&&(r.Vb=null);try{r.Qa.close&&r.Qa.close(r)}catch(xd){throw xd;}finally{sc[r.fd]=null}r.fd=null;if(++f===e){Y.get(W.pb)(W.id,e,c);for(r=0;r<d.length;++r)jd(d[r]);jd(c)}}};
p.readAsArrayBuffer(n);var u=Xb(m);d.push(u);x[c+4*k>>2]=u}if(W&&W.pb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Wb(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Kc();for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}},ld=a=>{if(W&&W.pb)return a.preventDefault(),!1};
function md(a,b){function c(){K=!1;var f=d.parentNode;zb()===f?(d.exitFullscreen=Kb,M&&d.requestPointerLock(),K=!0,N?Lb():(O(d),P())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),N?Mb():(O(d),P()));g.onFullScreen?.(K);g.onFullscreen?.(K)}M=a;N=b;"undefined"==typeof M&&(M=!0);"undefined"==typeof N&&(N=!1);var d=g.canvas;Ib||(Ib=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",
c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function nd(a,b,c){var d=od()?Lc:1;b&&c?(a.zb=b,a.ub=c):(b=a.zb,c=a.ub);var e=b,f=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(e/f<g.forcedAspectRatio?e=Math.round(f*g.forcedAspectRatio):f=Math.round(e/g.forcedAspectRatio));if(zb()===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/e,screen.height/f);e=Math.round(e*k);f=Math.round(f*k)}N&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(od()?(a.style.setProperty("width",
b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}function pd(a,b){const c=g.canvas.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;!od()&&W&&(a*=W.width/c.width,b*=W.height/c.height);return{x:a,y:b}}function qd(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}
function od(){return W?0<W.attributes[139276]:!1}function rd(){W&&(O(g.canvas,W.width,W.height),P())}function sd(){Lc=qd();W&&W.Rb&&Y.get(W.Rb)(W.id,Lc,Lc);rd()}g.requestAnimationFrame=Sa;g.pauseMainLoop=function(){E=null;Va++};g.resumeMainLoop=function(){Va++;var a=Ma,b=Na,c=Oa;Oa=null;db(c,0,!1,Xa,!0);Ua(a,b);E()};g.preMainLoop&&Za.push(g.preMainLoop);g.postMainLoop&&$a.push(g.postMainLoop);S=Array(4096);Fc(R,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");hc(259,{read:()=>0,write:(d,e,f,k)=>k,Sa:()=>0});Hc("/dev/null",259);gc(1280,jc);gc(1536,kc);Hc("/dev/tty",1280);Hc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Zb(a),b=a.byteLength);return a[--b]};V("random",c);V("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");Fc({Va(){var b=mc(a,"fd",16895,73);b.Qa={Sa:R.Qa.Sa};b.Pa={lookup(c,d){c=+d;var e=Dc(c);c={parent:null,Va:{Jb:"fake"},Pa:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(sc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();g.noExitRuntime&&(Ea=g.noExitRuntime);g.preloadPlugins&&(Bb=g.preloadPlugins);g.print&&(h=g.print);g.printErr&&(l=g.printErr);g.wasmBinary&&(ma=g.wasmBinary);
g.thisProgram&&(da=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
g.ccall=(a,b,c,d)=>{var e={string:p=>{var u=0;if(null!==p&&void 0!==p&&0!==p){u=hb(p)+1;var r=td(u);C(p,v,r,u);u=r}return u},array:p=>{var u=td(p.length);t.set(p,u);return u}};a=g["_"+a];var f=[],k=0;if(d)for(var n=0;n<d.length;n++){var m=e[c[n]];m?(0===k&&(k=ud()),f[n]=m(d[n])):f[n]=d[n]}c=a(...f);return c=function(p){0!==k&&vd(k);return"string"===b?p?B(v,p):"":"boolean"===b?!!p:p}(c)};
var yd,Wb,jd,vd,td,ud,ta,Y,zd={a:(a,b,c,d)=>z(`Assertion failed: ${a?B(v,a):""}, at: `+[b?b?B(v,b):"":"unknown filename",c,d?d?B(v,d):"":"unknown function"]),m:(a,b,c)=>{var d=new Ga(a);x[d.ib+16>>2]=0;x[d.ib+4>>2]=b;x[d.ib+8>>2]=c;Ha=a;Ia++;throw Ha;},T:()=>z(""),P:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=60*Math.max(f,e);w[b>>2]=Number(f!=e);b=k=>{var n=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(n/
60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(C(a,v,c,17),C(b,v,d,17)):(C(a,v,d,17),C(b,v,c,17))},U:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},S:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);sa();var e=1;break a}catch(f){}e=
void 0}if(e)return!0}return!1},ca:a=>{eval(a?B(v,a):"")},da:(a,b,c)=>{a=Y.get(a);db(a,b,c)},Q:(a,b)=>{var c=0,d=0,e;for(e of gb()){var f=b+c;x[a+d>>2]=f;c+=C(e,v,f,Infinity)+1;d+=4}return 0},R:(a,b)=>{var c=gb();x[a>>2]=c.length;a=0;for(var d of c)a+=hb(d)+1;x[b>>2]=a;return 0},W:()=>52,V:function(){return 70},B:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var k=x[b>>2],n=x[b+4>>2];b+=8;for(var m=0;m<n;m++){var p=a,u=v[k+m],r=ib[p];0===u||10===u?((1===p?h:l)(B(r)),r.length=0):r.push(u)}e+=n}x[d>>2]=e;return 0},
A:(a,b)=>{G.attachShader(H[a],I[b])},d:(a,b)=>{35051==a?G.kb=b:35052==a&&(G.lb=b);G.bindBuffer(a,lb[b])},h:(a,b)=>{G.bindFramebuffer(a,mb[b])},x:(a,b)=>{G.bindTexture(a,nb[b])},ea:a=>{G.bindVertexArray(ob[a])},c:(a,b,c,d)=>{c&&b?G.bufferData(a,v,d,c,b):G.bufferData(a,b,d)},u:a=>G.checkFramebufferStatus(a),X:a=>G.clear(a),Y:(a,b,c,d)=>G.clearColor(a,b,c,d),I:a=>{G.compileShader(I[a])},aa:()=>{var a=qb(H),b=G.createProgram();b.name=a;b.fb=b.cb=b.eb=0;b.yb=1;H[a]=b;return a},L:a=>{var b=qb(I);I[b]=G.createShader(a);
return b},k:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=lb[d];e&&(G.deleteBuffer(e),e.name=0,lb[d]=null,d==G.kb&&(G.kb=0),d==G.lb&&(G.lb=0))}},ka:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=mb[d];e&&(G.deleteFramebuffer(e),e.name=0,mb[d]=null)}},J:a=>{if(a){var b=H[a];b?(G.deleteProgram(b),b.name=0,H[a]=null):J||=1281}},q:a=>{if(a){var b=I[a];b?(G.deleteShader(b),I[a]=null):J||=1281}},la:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=nb[d];e&&(G.deleteTexture(e),e.name=0,nb[d]=null)}},
Z:a=>G.depthFunc(a),r:(a,b)=>{G.detachShader(H[a],I[b])},o:a=>G.disable(a),i:a=>{G.disableVertexAttribArray(a)},G:(a,b,c)=>{G.drawArrays(a,b,c)},C:(a,b,c,d)=>{G.drawElements(a,b,c,d)},_:a=>G.enable(a),f:a=>{G.enableVertexAttribArray(a)},v:(a,b,c,d,e)=>{G.framebufferTexture2D(a,b,c,nb[d],e)},e:(a,b)=>{rb(a,b,"createBuffer",lb)},z:(a,b)=>{rb(a,b,"createFramebuffer",mb)},y:(a,b)=>{rb(a,b,"createTexture",nb)},fa:(a,b)=>{rb(a,b,"createVertexArray",ob)},b:(a,b)=>G.getAttribLocation(H[a],b?B(v,b):""),M:(a,
b,c,d)=>{a=G.getProgramInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,v,d,b):0;c&&(w[c>>2]=b)},N:(a,b,c)=>{if(c)if(a>=kb)J||=1281;else if(a=H[a],35716==b)a=G.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.fb){var d=G.getProgramParameter(a,35718);for(b=0;b<d;++b)a.fb=Math.max(a.fb,G.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.fb}else if(35722==b){if(!a.cb)for(d=G.getProgramParameter(a,35721),b=0;b<d;++b)a.cb=Math.max(a.cb,G.getActiveAttrib(a,
b).name.length+1);w[c>>2]=a.cb}else if(35381==b){if(!a.eb)for(d=G.getProgramParameter(a,35382),b=0;b<d;++b)a.eb=Math.max(a.eb,G.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.eb}else w[c>>2]=G.getProgramParameter(a,b);else J||=1281},E:(a,b,c,d)=>{a=G.getShaderInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,v,d,b):0;c&&(w[c>>2]=b)},H:(a,b,c)=>{c?35716==b?(a=G.getShaderInfoLog(I[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=G.getShaderSource(I[a]),w[c>>2]=a?
a.length+1:0):w[c>>2]=G.getShaderParameter(I[a],b):J||=1281},j:(a,b)=>{b=b?B(v,b):"";if(a=H[a]){var c=a,d=c.$a,e=c.Qb,f;if(!d){c.$a=d={};c.Pb={};var k=G.getProgramParameter(c,35718);for(f=0;f<k;++f){var n=G.getActiveUniform(c,f);var m=n.name;n=n.size;var p=wb(m);p=0<p?m.slice(0,p):m;var u=c.yb;c.yb+=n;e[p]=[n,u];for(m=0;m<n;++m)d[u]=m,c.Pb[u++]=p}}c=a.$a;d=0;e=b;f=wb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Qb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||G.getUniformLocation(a,b)))return d}else J||=
1281;return-1},O:a=>{a=H[a];G.linkProgram(a);a.$a=0;a.Qb={}},F:(a,b,c,d,e,f,k)=>{if(G.kb)G.readPixels(a,b,c,d,e,f,k);else{var n=xb(f);k>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);G.readPixels(a,b,c,d,e,f,n,k)}},K:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var k=(k=x[c+4*f>>2])?B(v,k,d?x[d+4*f>>2]:void 0):"";e+=k}G.shaderSource(I[a],e)},w:(a,b,c,d,e,f,k,n,m)=>{if(G.lb)G.texImage2D(a,b,c,d,e,f,k,n,m);else if(m){var p=xb(n);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);G.texImage2D(a,b,c,d,e,f,k,n,p,m)}else{if(m){p=
xb(n);var u=e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[k-6402]||1)*p.BYTES_PER_ELEMENT+4-1&-4);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;G.texImage2D(a,b,c,d,e,f,k,n,m)}},n:(a,b,c)=>G.texParameteri(a,b,c),l:(a,b)=>{G.uniform1f(yb(a),b)},D:(a,b,c,d)=>{b&&G.uniformMatrix4fv(yb(a),!!c,qa,d>>2,16*b)},p:a=>{a=H[a];G.useProgram(a);G.Tb=a},g:(a,b,c,d,e,f)=>{G.vertexAttribPointer(a,b,c,!!d,e,f)},t:(a,b,c,d)=>G.viewport(a,
b,c,d),ia:(a,b,c,d)=>{var e;for(e=0;e<X.length&&null!==X[e];e++);0<e&&z("glfwCreateWindow only supports one window at time currently");var f=e+1;if(0>=a||0>=b)f=0;else{d?Jb():(O(g.canvas,a,b),P());for(e=0;e<X.length&&null==X[e];e++);d=g.canvas;var k=0<L[139265];e==X.length&&(k?Hb(d):Eb());!g.ctx&&k?f=0:(a=new Vb(f,a,b,d.width,d.height,c),f-1==X.length?X.push(a):X[f-1]=a,W=a,rd(),f=a.id)}return f},ja:()=>{if(X)return 1;L={...Oc};X=[];W=null;Lc=qd();window.addEventListener("gamepadconnected",Uc,!0);
window.addEventListener("gamepaddisconnected",Vc,!0);window.addEventListener("keydown",Wc,!0);window.addEventListener("keypress",Rc,!0);window.addEventListener("keyup",Xc,!0);window.addEventListener("blur",Yc,!0);Mc=window.matchMedia("(resolution: "+qd()+"dppx)");Mc.addEventListener("change",sd);var a=g.canvas;a.addEventListener("touchmove",Zc,!0);a.addEventListener("touchstart",cd,!0);a.addEventListener("touchcancel",dd,!0);a.addEventListener("touchend",dd,!0);a.addEventListener("mousemove",Zc,!0);
a.addEventListener("mousedown",cd,!0);a.addEventListener("mouseup",dd,!0);a.addEventListener("wheel",ed,!0);a.addEventListener("mousewheel",ed,!0);a.addEventListener("mouseenter",$c,!0);a.addEventListener("mouseleave",ad,!0);a.addEventListener("drop",kd,!0);a.addEventListener("dragover",ld,!0);Jb=md;Rb=pd;O=nd;Ub.push((b,c)=>{if(od()){var d=g.canvas;fd(d.clientWidth,d.clientHeight,b,c)}else fd(b,c,b,c)});return 1},ga:()=>0,$:()=>0,ba:()=>{},ha:()=>{window.removeEventListener("gamepadconnected",Uc,
!0);window.removeEventListener("gamepaddisconnected",Vc,!0);window.removeEventListener("keydown",Wc,!0);window.removeEventListener("keypress",Rc,!0);window.removeEventListener("keyup",Xc,!0);window.removeEventListener("blur",Yc,!0);var a=g.canvas;a.removeEventListener("touchmove",Zc,!0);a.removeEventListener("touchstart",cd,!0);a.removeEventListener("touchcancel",dd,!0);a.removeEventListener("touchend",dd,!0);a.removeEventListener("mousemove",Zc,!0);a.removeEventListener("mousedown",cd,!0);a.removeEventListener("mouseup",
dd,!0);a.removeEventListener("wheel",ed,!0);a.removeEventListener("mousewheel",ed,!0);a.removeEventListener("mouseenter",$c,!0);a.removeEventListener("mouseleave",ad,!0);a.removeEventListener("drop",kd,!0);a.removeEventListener("dragover",ld,!0);Mc&&Mc.removeEventListener("change",sd);a.width=a.height=1;W=X=null},s:(a,b)=>{L[a]=b}};
function Ad(){function a(){g.calledRun=!0;if(!q){if(!g.noFSInit&&!uc){var b,c;uc=!0;b??=g.stdin;c??=g.stdout;d??=g.stderr;b?V("stdin",b):Ic("/dev/tty","/dev/stdin");c?V("stdout",null,c):Ic("/dev/tty","/dev/stdout");d?V("stderr",null,d):Ic("/dev/tty1","/dev/stderr");Jc("/dev/stdin",0);Jc("/dev/stdout",1);Jc("/dev/stderr",1)}Bd.na();vc=!1;g.onRuntimeInitialized?.();if(!g.noInitialRun){var d=yd;try{var e=d(0,0);na=e;Ka(e)}catch(f){Ja(f)}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)e=
g.postRun.shift(),Aa.push(e);za(Aa)}}if(0<A)Da=Ad;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ca();za(Ba);0<A?Da=Ad:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()}}var Bd;
(async function(){function a(c){c=Bd=c.exports;g._setMeshgenParams=c.pa;g._updateShaderFunction=c.qa;g._regenerateMesh=c.ra;g._decimateMesh=c.sa;g._setRenderNeeded=c.ta;g._translateState=c.ua;g._scaleState=c.va;g._resizeWindow=c.wa;g._resetState=c.xa;g._setScreenCenter=c.ya;g._setMeshShowEdges=c.za;g._setMeshSmoothShading=c.Aa;g._setColorSource=c.Ba;g._isModelEmpty=c.Ca;g._getFileSize=c.Da;g._generateSTL=c.Ea;g._generatePLY=c.Fa;g._generateOBJ=c.Ga;g._generateGLB=c.Ha;yd=g._main=c.Ia;Wb=c.Ja;jd=c.Ka;
vd=c.La;td=c.Ma;ud=c.Na;ta=c.ma;Y=c.oa;sa();A--;g.monitorRunDependencies?.(A);0==A&&Da&&(c=Da,Da=null,c());return Bd}A++;g.monitorRunDependencies?.(A);var b={a:zd};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=g.locateFile?g.locateFile("module.wasm",ha):ha+"module.wasm";return a((await xa(b)).instance)})();Ad();
